### ISSUE TITLE
Critical Bug: Wrong percentage indications?

### ISSUE THREAD

**Issue by oz123** [variety/variety#69] opened 2015-02-18 12:21 UTC
Sometime variety would out put stuff like this:
````
[66] oti@core-dev:~/Software/variety  [master]  $ /srv/mongodb/bin/mongo  --eval "var db_name = 'client'; var collection = 'rules'" variety.js
MongoDB shell version: 2.6.4
connecting to: test
Variety: A MongoDB Schema Analyzer
Version 1.4.1, released 14 Oct 2014
Using query of { }
Using limit of 84
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of ascii
Using persistResults of false
removing leaf arrays in results collection, and getting percentages
+----------------------------------------------------------------------------------------------+
| key                                      | types          | occurrences | percents           |
| ---------------------------------------- | -------------- | ----------- | ------------------ |
| rules.XX.filter                          | Object         | 5907        | 7032.142857142857  |
| rules.XX.filter.account                  | String         | 5907        | 7032.142857142857  |
| rules.XX.modify                          | Object         | 5907        | 7032.142857142857  |
| rules.XX.name                            | String         | 5907        | 7032.142857142857  |
| rules.XX.modify.channel                  | String         | 5012        | 5966.666666666666  |
| rules.XX.modify.sub_channel              | String         | 5012        | 5966.666666666666  |
| rules.XX.modify.sub2_channel             | String         | 4976        | 5923.809523809524  |
| rules.XX.modify.top_channel              | String         | 4592        | 5466.666666666666  |
| rules.XX.filter.channel                  | String         | 4278        | 5092.857142857143  |
| rules.XX.filter.campaign                 | String         | 3816        | 4542.857142857143  |
| rules.XX.modify.paid_performance_channel | Boolean,String | 1987        | 2365.4761904761904 |
| rules.XX.modify.exclude                  | Boolean        | 1164        | 1385.7142857142858 |
| rules.XX.modify.sea_brand                | String,Boolean | 567         | 675                |
| rules.XX.modify.cpc                      | Number         | 476         | 566.6666666666667  |
| rules.XX.modify.cost                     | Number         | 281         | 334.5238095238095  |
| rules.XX.modify.campaignId               | String         | 168         | 200                |
| rules.XX.modify.crr                      | Number         | 159         | 189.28571428571428 |
| _id                                      | ObjectId       | 84          | 100                |
| author                                   | String         | 84          | 100                |
| rules                                    | Array          | 84          | 100                |
| date                                     | String         | 27          | 32.142857142857146 |
| rules.XX.modify.sea_brand_non_brand      | Boolean        | 4           | 4.761904761904762  |
+----------------------------------------------------------------------------------------------+
```

This is true for values inside arrays. Notice here the rules.XX.modify is appearing 5907 times in 84 records? This is exactly `5907/84*100=7032.14285714285`.

**Comment by JamesCropcho** [comment] 2015-02-18 18:51
Thanks, Oz. Yes, this certainly does look like quite a bug. Here it is presumably because with `rules.XX.modify`, there are documents with more than one of the array element, and each instance is being counted as within the document, rather than simply incrementing by one for the document as a whole.

I'll look at this when I'm able, but I also encourage anybody else to look at this, too- I'm marking this as critical.

One smaller step which could be taken as a first, could be to create a failing test. I imagine this would be easy in this scenario.

-James

**Comment by todvora** [comment] 2015-02-19 18:36
Hi,

I was able to reproduce this error and write test for it. The fix itself is pretty simple. Analysis now runs in two steps, first step aggregates keys from one object, merging duplicities. Second step then aggregates this document fingerprints. 

Could you please review the PR https://github.com/variety/variety/pull/72 ? Oz, may I ask you for testing on the collection described above? Does it solve the incorrect percents?

Thank you!

Tomas

**Comment by oz123** [comment] 2015-02-23 12:40
@todvora 
I confirm your patch works. 
```
~/Software/variety_tv/variety  [unnamed-objects-counts]  $ /srv/mongodb/bin/mongo  <IP>/admin -u $USER -p  --eval "var db_name = 'client'; var collection = 'rules'" variety.js
MongoDB shell version: 2.6.4
Enter password: 
connecting to: <IP>/admin
Variety: A MongoDB Schema Analyzer
Version 1.4.1, released 14 Oct 2014
Using query of { }
Using limit of 142
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of ascii
Using persistResults of false
+----------------------------------------------------------------------------------------------+
| key                                      | types          | occurrences | percents           |
| ---------------------------------------- | -------------- | ----------- | ------------------ |
| _id                                      | ObjectId       | 142         | 100                |
| rules                                    | Array          | 142         | 100                |
| rules.XX.filter                          | Object         | 142         | 100                |
| rules.XX.filter.account                  | String         | 142         | 100                |
| rules.XX.filter.campaign                 | String         | 142         | 100                |
| rules.XX.filter.channel                  | String         | 142         | 100                |
| rules.XX.modify                          | Object         | 142         | 100                |
| rules.XX.modify.campaignId               | String         | 142         | 100                |
| rules.XX.modify.channel                  | String         | 142         | 100                |
| rules.XX.modify.cpc                      | Number         | 142         | 100                |
| rules.XX.modify.exclude                  | Boolean        | 142         | 100                |
| rules.XX.modify.sub2_channel             | String         | 142         | 100                |
| rules.XX.modify.sub_channel              | String         | 142         | 100                |
| rules.XX.name                            | String         | 142         | 100                |
| rules.XX.modify.crr                      | Number         | 139         | 97.88732394366197  |
| author                                   | String         | 130         | 91.54929577464789  |
| rules.XX.modify.paid_performance_channel | Boolean,String | 117         | 82.3943661971831   |
| rules.XX.modify.top_channel              | String         | 117         | 82.3943661971831   |
| rules.XX.modify.sea_brand                | Boolean,String | 116         | 81.69014084507042  |
| date                                     | String         | 65          | 45.774647887323944 |
| rules.XX.modify.cost                     | Number         | 43          | 30.281690140845072 |
| rules.XX.modify.sea_brand_non_brand      | Boolean        | 1           | 0.704225352112676  |
+----------------------------------------------------------------------------------------------+

 $ git log -n 1 -s
commit a24d38c8b1a93c3ac9672132b3a8165e7b6b6409
Author: Tomas Dvorak <todvora@gmail.com>
Date:   Fri Feb 20 14:13:01 2015 +0100

    Code refactoring: processing pipe instead of forEach cycles
```

**Comment by oz123** [comment] 2015-02-23 12:41
Sorry, this issue should be closed once the code is merged.

**Comment by JamesCropcho** [comment] 2015-02-25 22:02
Alright @oz123 and @todvora, I am closing this issue because @oz123 confirmed the patch works for him, and it will be merged imminmently. Feel free to re-open for any reason.

Thanks for the assistance on Variety, Oz!  --James

**Closed by JamesCropcho** 2015-02-25 22:02 UTC
Labels: bug
