### ISSUE TITLE
toFixed() causes RangeError

### ISSUE THREAD

**Issue by TimLudwinski** [variety/variety#118] opened 2016-05-09 18:31 UTC
On line 350 `toFixed()` can cause a RangeError when `maxDigits` is greater than 20.  Apparently the `significantDigits()` function is returning a value greater than 20.  

We probably just want to cap `maxDigits` at 20.  

I'm using the `2.6.11` version of mongo client and `2.4` mongo server.

**Comment by todvora** [comment] 2016-05-10 05:24
Hi Tim,
Thanks for the bug report. Your suggested solution seems the right thing to do. But I would like to write some tests first and cannot reproduce it myself. Would it be possible to provide a collection sample that causes this error?

**Comment by TimLudwinski** [comment] 2016-05-11 22:09
Sorry, the collection that cause this error had 3 million items.  Besides that I dropped the collection after running variety on it with the `logKeysContinuously` option.

**Comment by TimLudwinski** [comment] 2016-05-11 22:18
The following `percentContaining`, for example, might cause this error:
```
var percentContaining = 1 * 100 / 3834892;
percentContaining.toString(); // 0.000026076353649594305 - 22 digits
percentContaining.toFixed(22); // RangeError
```

**Comment by todvora** [comment] 2016-05-12 16:30
Thanks for your instructions, I'll see, what can be done with it. 

Regards,
Tomas

**Comment by JamesCropcho** [comment] 2016-05-19 15:21
Hello you two, it looks like there is still some active movement on this—great! Let's keep the ticket/issue open.

**Comment by TimLudwinski** [comment] 2016-06-15 13:38
I think this issue is fixed.

**Comment by JamesCropcho** [comment] 2016-06-15 18:00
Looks that way, Tim ( @timludwinski ). I'll close this. Thanks for noticing.

—James

**Closed by JamesCropcho** 2016-06-15 18:00 UTC
Labels: bug
